# Generated by Django 4.1.5 on 2023-01-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='snow', max_length=30, unique=True),
        ),
    ]
