# Generated by Django 4.1.5 on 2023-02-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_squashed_0004_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_permanent_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
